name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Build
        run: |
          npm install
          npm run build
        env:
          REACT_APP_GOOGLE_MAPS_API: ${{ secrets.REACT_APP_GOOGLE_MAPS_API }}
          REACT_APP_GOOGLE_ANALYTICS_TRACKING: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_TRACKING }}

      - name: Deploy
        run: |
          npm run deploy
        env:
          REACT_APP_GOOGLE_MAPS_API: ${{ secrets.REACT_APP_GOOGLE_MAPS_API }}
          REACT_APP_GOOGLE_ANALYTICS_TRACKING: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_TRACKING }}