# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - master
        gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Build
      run: |
        npm install
        npm run build
      env:
        REACT_APP_GOOGLE_MAPS_API: ${{ secrets.REACT_APP_GOOGLE_MAPS_API }}
        REACT_APP_GOOGLE_ANALYTICS_TRACKING: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_TRACKING }}

    - name: Deploy
      run: |
        npm run deploy
      env:
        REACT_APP_GOOGLE_MAPS_API: ${{ secrets.REACT_APP_GOOGLE_MAPS_API }}
        REACT_APP_GOOGLE_ANALYTICS_TRACKING: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_TRACKING }}
